version: '3.8'

services:
  go_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_go_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./src/discordbot.db:/app/data/discordbot.db
    env_file:
      - .env 
