name: Deploy Go App

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      APP_ID: ${{ secrets.APP_ID }}
      CLIENT_SECRET: ${{ secrets.BOT_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v1
        with:
          go-version: 1.23.x

      - name: Build the Go app
        run: |
          cd $GITHUB_WORKSPACE/Discord-Bot-Practice  # If your files are in a subdirectory
          go build -o dist/discord-bot .

      - name: Deploy the application
        run: |
          echo "Deploying application..."
          ./dist/discord-bot
