name: Deploy Go App in Docker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Stop and Remove Existing Containers (if any)
        run: |
          docker-compose down && docker rm $(docker ps -a | grep my_go_app | awk '{print $1}')

      - name: Pull Latest Image (For Caching)
        run: docker pull my_go_app:latest || true

      - name: Create .env File
        run: |
          echo "DB_PATH=/app/discordbot.db" > .env
          echo "APP_ENV=production" >> .env
          echo "APP_ID=${{ secrets.APP_ID }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env

      - name: Build and Start Services
        run: docker-compose up -d --build

      - name: Verify Running Containers
        run: docker ps
