name: Deploy Go App

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Set up Go environment
        uses: actions/setup-go@v1
        with:
          go-version: 1.23.4

      - name: Create .env file
        run: |
          echo "APP_ID=${{ secrets.APP_ID }}" > $GITHUB_WORKSPACE/.env
          echo "CLIENT_SECRET=${{ secrets.BOT_TOKEN }}" >> $GITHUB_WORKSPACE/.env

      - name: Build the Go app
        run: |
          cd $GITHUB_WORKSPACE/src
          go build -o ./discord-bot .

      - name: Deploy the application
        run: |
          echo "Deploying application..."
          cd $GITHUB_WORKSPACE/src
          ./discord-bot
